# Libraries

In [1]:
import pandas as pd
import numpy as np
import pickle

# Load Datasets

In [139]:
path = 'D://DTU//DTU_Courses//Second Semester//Advanced BA//Project//ABA-Spring2023//Data//Pickle Files//'

In [140]:
with open(path+'disease_Proc_df.pickle', 'rb') as f:
    disease_df = pickle.load(f)

In [120]:
with open(path+'pollution_Proc_df.pickle', 'rb') as f:
    pollution_annual_df = pickle.load(f)

In [121]:
with open(path+'Tax_Proc_df.pickle', 'rb') as f:
    tax_df = pickle.load(f)

In [122]:
with open(path+'demog_Proc_df.pickle', 'rb') as f:
    demog_df = pickle.load(f)

# Preprocessing

### Disease

In [266]:
disease_df.groupby(['Question']).size().reset_index().rename(columns={0:'count'}).sort_values('count',ascending=False)

,Question,count
34,"Invasive cancer (all sites combined), incidence",6240
9,"Cancer of the lung and bronchus, incidence",6240
39,"Invasive cancer of the prostate, incidence",6240
38,"Invasive cancer of the oral cavity or pharynx, incidence",6240
37,"Invasive cancer of the female breast, incidence",6240
12,"Cancer of the prostate, mortality",6240
11,"Cancer of the oral cavity and pharynx, mortality",6240
10,"Cancer of the lung and bronchus, mortality",6240
8,"Cancer of the female cervix, mortality",6240
42,"Melanoma, mortality",6240
7,"Cancer of the female breast, mortality",6240
6,"Cancer of the colon and rectum (colorectal), mortality",6240
5,"Cancer of the colon and rectum (colorectal), incidence",6240
36,"Invasive cancer of the cervix, incidence",6240
35,"Invasive cancer (all sites combined), mortality",6240
40,"Invasive melanoma, incidence",6240
23,Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligib...,1716
46,Mortality from heart failure,1716
43,Mortality from cerebrovascular disease (stroke),1716
44,Mortality from coronary heart disease,1716
45,Mortality from diseases of the heart,1716
26,Hospitalization for heart failure among Medicare-eligible persons aged >= 65 years,1716
47,Mortality from total cardiovascular diseases,1716
48,Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45...,1716
49,Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among a...,1716
25,Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medica...,1716
0,Asthma mortality rate,1320
14,Current asthma prevalence among adults aged >= 18 years,1188
66,Recent mentally unhealthy days among adults aged >= 18 years,1188
30,Influenza vaccination among noninstitutionalized adults aged 18-64 years with asthma,1184
62,Prevalence of chronic obstructive pulmonary disease among adults >= 45 years,1184
61,Prevalence of chronic obstructive pulmonary disease among adults >= 18,1184
63,Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary di...,1181
52,Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with asthma,1180
29,Influenza vaccination among noninstitutionalized adults aged 18-64 years with a history of coron...,1178
31,Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructiv...,1174
32,Influenza vaccination among noninstitutionalized adults aged >= 65 years with a history of coron...,1174
64,Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmon...,1173
53,Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstruc...,1172
54,Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with a history of co...,1162
33,Influenza vaccination among noninstitutionalized adults aged >= 65 years with asthma,1162
55,Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with asthma,1162
51,Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with a history of co...,1129
20,High cholesterol prevalence among adults aged >= 18 years,644
67,Taking medicine for high blood pressure control among adults aged >= 18 years with high blood pr...,644
13,Cholesterol screening among adults aged >= 18 years,644
3,Awareness of high blood pressure among adults aged >= 18 years,644
2,At least 14 recent mentally unhealthy days among women aged 18-44 years,594
68,Timeliness of routine health care checkup among women aged 18-44 years,594
1,Asthma prevalence among women aged 18-44 years,590
59,Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonar...,578
60,Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pu...,572
41,Mammography use among women aged 50-74 years,566
18,"Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years",566
50,Papanicolaou smear use among adult women aged 21-65 years,550
24,Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis,534
22,Hospitalization for chronic obstructive pulmonary disease as any diagnosis,534
21,Hospitalization for acute myocardial infarction,534
27,Hospitalization for stroke,534
28,Hospitalizations for asthma,531
19,Folic acid supplementation,341
17,Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis,330
16,Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis,330
15,Emergency department visit rate for asthma,327
4,Awareness of high blood pressure among women aged 18-44 years,322
56,Postpartum checkup,319
65,Recent Papanicolaou smear use among women aged 21-44 years,275
57,Postpartum depressive symptoms,69
58,Pre-pregnancy hypertension,9

In [59]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 100)

In [291]:
disease_df = disease_df.reset_index()
disease_df = disease_df.drop(['index','YearStart','YearEnd','DataSource','Response','DataValue','DataValueFootnoteSymbol','DatavalueFootnote','StratificationCategory2','Stratification2','StratificationCategory3','Stratification3','GeoLocation','ResponseID','LocationID','DataValueTypeID','StratificationCategoryID1','StratificationID1','StratificationCategoryID2','StratificationID2','StratificationCategoryID3','StratificationID3','Year_Diff'],axis=1)
disease_df.dropna(subset=['DataValueAlt'],inplace=True)

In [292]:
disease_df = disease_df[disease_df['StratificationCategory1']=='Overall']

In [293]:
disease_df = disease_df[disease_df['Topic'].isin(['Asthma','Cancer','Cardiovascular Disease','Chronic Obstructive Pulmonary Disease','Reproductive Health','Mental Health'])]

In [295]:
disease_df = disease_df[disease_df['Question'].isin(['Cancer of the lung and bronchus, incidence','Cancer of the colon and rectum (colorectal), incidence','Invasive cancer of the oral cavity or pharynx, incidence','Invasive cancer of the female breast, incidence','Invasive cancer of the prostate, incidence','Invasive melanoma, incidence','Invasive cancer of the cervix, incidence']) ]

In [296]:
disease_df = disease_df[disease_df['DataValueUnit'].isna()==False]

In [301]:
disease_df = disease_df.pivot_table(index=['LocationAbbr','LocationDesc','Year'],columns='QuestionID',values='DataValueAlt').reset_index()
disease_df = disease_df.rename_axis(None, axis=1)

In [306]:
disease_df.columns = ['State','StateDesc','Year','CAN10_1','CAN11_1','CAN5_1','CAN6_1','CAN7_1','CAN8_1','CAN9_1']

In [308]:
disease_df.to_pickle("D://DTU\DTU_Courses//Second Semester//Advanced BA//Project//ABA-Spring2023//Data//Pickle Files//Disease_Proc_df.pickle")

### Pollution

In [312]:
pollution_annual_df

,SITE_ID,SITE_NAME,STATE,COUNTY,LATITUDE,LONGITUDE,MAPID,YEAR,PRECIP,N_WET_NH4,N_WET_NO3,N_WET,N_DRY_HNO3,N_DRY_NO3,N_DRY_TNO3,N_DRY_NH4,N_DRY_NH3,N_DRY_NH3NET,N_DRY_NOM,N_DRY_NRED,N_DRY_NOXI,N_DRY,N_TOTAL_NRED,N_TOTAL_NOXI,N_TOTAL,S_WET_SO4,S_WET,S_DRY_SO2,S_DRY_SO4,S_DRY,S_TOTAL,NA_DRY,NA_WET,NA_TOTAL,MG_DRY,MG_WET,MG_TOTAL,K_DRY,K_WET,K_TOTAL,CA_DRY,CA_WET,CA_TOTAL,CL_DRY,CL_WET,CL_TOTAL
0,ABT147,Abington,CT,Windham,41.840460,-72.010368,"Hampton, CT",2001.0,95.655,1.306,2.395,3.701,6.241,0.169,6.410,0.299,0.808,0.240,1.841,1.107,8.251,9.358,2.413,10.646,13.059,4.251,4.251,5.811,0.347,6.158,10.409,0.339,1.574,1.912,0.048,0.212,0.260,0.040,0.155,0.195,0.120,0.712,0.833,0.157,2.821,2.978
1,ABT147,Abington,CT,Windham,41.840460,-72.010368,"Hampton, CT",2002.0,114.430,1.749,2.989,4.738,5.883,0.177,6.060,0.257,0.808,0.240,1.841,1.065,7.900,8.965,2.814,10.889,13.703,4.925,4.925,4.382,0.310,4.693,9.618,0.381,1.590,1.972,0.056,0.233,0.289,0.045,0.269,0.314,0.114,0.724,0.838,0.157,2.901,3.058
2,ABT147,Abington,CT,Windham,41.840460,-72.010368,"Hampton, CT",2003.0,126.995,1.555,2.388,3.943,4.535,0.165,4.699,0.226,0.833,0.347,1.736,1.059,6.436,7.494,2.614,8.823,11.437,4.209,4.209,3.579,0.298,3.878,8.087,0.435,3.191,3.626,0.057,0.390,0.446,0.072,0.191,0.263,0.094,0.660,0.753,0.157,5.942,6.099
3,ABT147,Abington,CT,Windham,41.840460,-72.010368,"Hampton, CT",2004.0,126.351,1.540,2.425,3.965,4.613,0.181,4.794,0.265,0.738,0.222,1.609,1.002,6.403,7.405,2.542,8.828,11.370,4.219,4.219,3.705,0.306,4.011,8.230,0.396,2.025,2.421,0.052,0.248,0.300,0.043,0.143,0.186,0.091,0.571,0.662,0.224,3.686,3.910
4,ABT147,Abington,CT,Windham,41.840460,-72.010368,"Hampton, CT",2005.0,137.747,1.217,2.016,3.233,4.576,0.145,4.720,0.244,0.733,0.207,1.380,0.977,6.100,7.078,2.194,8.116,10.311,3.916,3.916,3.698,0.328,4.026,7.942,0.400,4.989,5.388,0.053,0.598,0.651,0.046,0.237,0.283,0.108,0.677,0.784,0.252,9.138,9.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,YOS404,Yosemite NP - Turtleback Dome,CA,Mariposa,37.713251,-119.706196,NaN,2016.0,111.357,1.176,0.458,1.634,2.304,0.119,2.423,0.186,2.399,2.294,0.188,2.585,2.611,5.196,3.761,3.069,6.830,0.500,0.500,0.428,0.122,0.550,1.050,0.223,0.591,0.814,0.048,0.101,0.148,0.084,0.135,0.219,0.171,0.438,0.608,0.130,1.004,1.135
2196,YOS404,Yosemite NP - Turtleback Dome,CA,Mariposa,37.713251,-119.706196,NaN,2017.0,169.564,1.305,0.626,1.932,2.488,0.167,2.655,0.264,2.187,2.073,0.185,2.451,2.840,5.292,3.757,3.467,7.224,0.653,0.653,0.337,0.148,0.486,1.138,0.212,0.765,0.977,0.055,0.103,0.159,0.136,0.122,0.259,0.244,0.336,0.579,0.102,1.491,1.594
2197,YOS404,Yosemite NP - Turtleback Dome,CA,Mariposa,37.713251,-119.706196,NaN,2018.0,90.299,1.012,0.483,1.495,2.601,0.273,2.874,0.292,2.187,2.073,0.185,2.479,3.059,5.538,3.491,3.542,7.033,0.344,0.344,0.428,0.149,0.577,0.921,0.252,0.455,0.707,0.085,0.073,0.159,0.220,0.113,0.333,0.488,0.373,0.861,0.095,0.809,0.905
2198,YOS404,Yosemite NP - Turtleback Dome,CA,Mariposa,37.713251,-119.706196,NaN,2019.0,125.660,1.856,0.664,2.520,2.211,0.137,2.348,0.201,2.187,2.073,0.185,2.388,2.533,4.921,4.245,3.197,7.442,0.579,0.579,0.289,0.129,0.418,0.997,0.194,1.046,1.240,0.053,0.141,0.194,0.080,0.227,0.307,0.199,0.547,0.746,0.073,1.799,1.872
2199,YOS404,Yosemite NP - Turtleback Dome,CA,Mariposa,37.713251,-119.706196,NaN,2020.0,48.580,0.761,0.258,1.019,2.549,0.259,2.808,0.351,2.187,2.073,0.185,2.538,2.994,5.532,3.299,3.252,6.551,0.242,0.242,0.372,0.154,0.526,0.768,0.209,0.332,0.541,0.074,0.044,0.118,0.201,0.060,0.261,0.411,0.166,0.577,0.084,0.551,0.635

In [313]:
pollution_annual_df.columns

Index(['SITE_ID', 'SITE_NAME', 'STATE', 'COUNTY', 'LATITUDE', 'LONGITUDE',
       'MAPID', 'YEAR', 'PRECIP', 'N_WET_NH4', 'N_WET_NO3', 'N_WET',
       'N_DRY_HNO3', 'N_DRY_NO3', 'N_DRY_TNO3', 'N_DRY_NH4', 'N_DRY_NH3',
       'N_DRY_NH3NET', 'N_DRY_NOM', 'N_DRY_NRED', 'N_DRY_NOXI', 'N_DRY',
       'N_TOTAL_NRED', 'N_TOTAL_NOXI', 'N_TOTAL', 'S_WET_SO4', 'S_WET',
       'S_DRY_SO2', 'S_DRY_SO4', 'S_DRY', 'S_TOTAL', 'NA_DRY', 'NA_WET',
       'NA_TOTAL', 'MG_DRY', 'MG_WET', 'MG_TOTAL', 'K_DRY', 'K_WET', 'K_TOTAL',
       'CA_DRY', 'CA_WET', 'CA_TOTAL', 'CL_DRY', 'CL_WET', 'CL_TOTAL'],
      dtype='object')

In [314]:
pollution_annual_df = pollution_annual_df.drop(['SITE_ID', 'SITE_NAME', 'COUNTY', 'MAPID', 'LATITUDE', 'LONGITUDE', 'LONGITUDE', 'N_TOTAL_NRED', 'N_TOTAL_NOXI', 'N_TOTAL', 'S_TOTAL', 'K_TOTAL', 'MG_TOTAL', 'NA_TOTAL', 'CA_TOTAL', 'CL_TOTAL'], axis=1)

In [327]:
pollution_annual_df[pollution_annual_df['S_WET_SO4'].isna()]['STATE'].unique()

array(['AK', 'ON', 'HI', 'FL', 'VI'], dtype=object)

In [332]:
pollution_annual_df[(pollution_annual_df['STATE'] == 'WY') & (pollution_annual_df['YEAR'] == 2005)]

,STATE,YEAR,PRECIP,N_WET_NH4,N_WET_NO3,N_WET,N_DRY_HNO3,N_DRY_NO3,N_DRY_TNO3,N_DRY_NH4,N_DRY_NH3,N_DRY_NH3NET,N_DRY_NOM,N_DRY_NRED,N_DRY_NOXI,N_DRY,S_WET_SO4,S_WET,S_DRY_SO2,S_DRY_SO4,S_DRY,NA_DRY,NA_WET,MG_DRY,MG_WET,K_DRY,K_WET,CA_DRY,CA_WET,CL_DRY,CL_WET
164,WY,2005.0,26.806,0.460,0.415,0.874,0.340,0.033,0.373,0.037,0.087,-0.049,0.160,0.124,0.533,0.657,0.451,0.451,0.286,0.024,0.309,0.020,0.092,0.013,0.050,0.025,0.054,0.100,0.439,0.016,0.138
244,WY,2005.0,32.807,0.763,0.614,1.377,0.557,0.050,0.607,0.045,0.112,-0.044,0.233,0.157,0.840,0.996,0.627,0.627,0.322,0.031,0.353,0.022,0.093,0.017,0.064,0.028,0.079,0.146,0.629,0.019,0.154
484,WY,2005.0,130.327,0.928,1.392,2.320,1.447,0.063,1.510,0.103,0.424,0.000,0.246,0.528,1.757,2.284,1.364,1.364,0.224,0.077,0.301,0.047,0.262,0.024,0.118,0.033,0.107,0.141,1.052,0.042,0.329
764,WY,2005.0,38.968,0.910,0.726,1.636,0.685,0.064,0.749,0.058,0.112,-0.095,0.249,0.170,0.999,1.168,0.739,0.739,0.388,0.038,0.426,0.026,0.106,0.024,0.075,0.048,0.094,0.257,0.742,0.022,0.178
1344,WY,2005.0,49.770,1.197,0.973,2.170,1.226,0.129,1.355,0.116,0.600,0.309,0.255,0.716,1.610,2.326,0.954,0.954,0.434,0.063,0.497,0.037,0.117,0.033,0.093,0.056,0.123,0.381,1.018,0.032,0.229
1544,WY,2005.0,34.632,0.645,0.743,1.388,1.055,0.054,1.108,0.098,0.458,0.391,0.119,0.556,1.228,1.783,0.831,0.831,0.220,0.062,0.283,0.053,0.184,0.027,0.093,0.045,0.075,0.169,0.821,0.034,0.259
1803,WY,2005.0,46.608,0.863,0.724,1.587,0.385,0.034,0.419,0.035,0.209,-0.035,0.231,0.244,0.650,0.894,0.815,0.815,0.329,0.025,0.354,0.019,0.125,0.014,0.084,0.023,0.109,0.110,0.672,0.016,0.196
2164,WY,2005.0,63.752,0.913,0.714,1.627,0.303,0.025,0.328,0.037,0.787,0.696,0.178,0.823,0.506,1.329,0.664,0.664,0.862,0.023,0.885,0.014,0.251,0.008,0.079,0.017,0.121,0.051,0.717,0.014,0.438

In [335]:
pollution_annual_df = pollution_annual_df.groupby(['YEAR', 'STATE']).mean().reset_index()

In [345]:
pollution_annual_df = pollution_annual_df[pollution_annual_df['N_WET_NH4'].isna() == False]

In [350]:
pollution_annual_df

,YEAR,STATE,PRECIP,N_WET_NH4,N_WET_NO3,N_WET,N_DRY_HNO3,N_DRY_NO3,N_DRY_TNO3,N_DRY_NH4,N_DRY_NH3,N_DRY_NH3NET,N_DRY_NOM,N_DRY_NRED,N_DRY_NOXI,N_DRY,S_WET_SO4,S_WET,S_DRY_SO2,S_DRY_SO4,S_DRY,NA_DRY,NA_WET,MG_DRY,MG_WET,K_DRY,K_WET,CA_DRY,CA_WET,CL_DRY,CL_WET
1,2001.0,AL,131.225000,2.506000,2.165000,4.67200,4.173000,0.286000,4.460000,0.398000,1.535000,0.791000,1.932000,1.933000,6.391000,8.324000,4.921000,4.921000,6.638000,0.318000,6.956000,0.196000,1.27300,0.046000,0.22300,0.060000,0.551000,0.184000,0.866000,0.106000,2.245000
2,2001.0,AR,151.199000,1.507000,2.241000,3.74800,3.314000,0.077000,3.391000,0.233000,1.217000,0.678000,1.516000,1.450000,4.907000,6.356000,4.147000,4.147000,1.446000,0.244000,1.690000,0.208000,1.44200,0.038000,0.24000,0.048000,0.526000,0.135000,1.754000,0.092000,2.448000
3,2001.0,AZ,34.533333,0.549667,0.827333,1.37700,1.498000,0.107333,1.605667,0.113667,0.365667,0.131667,0.253000,0.479333,1.858333,2.337667,0.823667,0.823667,0.369667,0.104333,0.474333,0.126333,0.23300,0.035333,0.09500,0.038667,0.140667,0.269667,0.934667,0.044000,0.423667
4,2001.0,CA,58.153625,1.176000,0.892625,2.06875,3.764625,0.248125,4.012500,0.226250,2.296750,2.054875,0.449625,2.522625,4.462250,6.984875,0.590750,0.590750,0.419875,0.124625,0.544375,0.288750,0.73975,0.058000,0.10500,0.070250,0.104875,0.261250,0.467375,0.088375,1.249750
5,2001.0,CO,55.322000,0.772000,1.045000,1.81650,1.412250,0.224000,1.636250,0.175000,0.331500,0.198750,0.282750,0.506500,1.919250,2.425500,0.842750,0.842750,0.274500,0.133000,0.407500,0.095000,0.15750,0.038500,0.08650,0.048500,0.095000,0.275250,0.910750,0.048250,0.270750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,2020.0,VT,118.453500,1.962500,1.584000,3.54700,1.286000,0.105500,1.391500,0.141000,1.460000,1.300500,0.468000,1.600500,1.859500,3.460500,1.066500,1.066500,0.247000,0.097000,0.344000,0.158500,0.65050,0.039000,0.23350,0.040500,0.347000,0.160500,1.258500,0.145500,1.145000
856,2020.0,WA,150.606750,0.770000,0.718250,1.48825,0.841250,0.044750,0.886000,0.074500,0.641750,-0.171500,0.414000,0.716000,1.299750,2.015750,0.720750,0.720750,0.227250,0.080500,0.308000,0.125750,2.65325,0.057500,0.31725,0.044750,0.256500,0.064500,0.469250,0.114250,4.828000
857,2020.0,WI,89.840000,4.528000,1.534000,6.06200,1.163000,0.140000,1.303000,0.143000,3.733000,3.415000,0.422000,3.876000,1.724000,5.601000,1.117000,1.117000,0.307000,0.056000,0.362000,0.054000,0.30500,0.060000,0.35000,0.043000,0.269000,0.370000,3.310000,0.073000,0.512000
858,2020.0,WV,134.437000,1.895500,1.376500,3.27150,1.266000,0.070500,1.337000,0.145000,1.523000,1.121000,0.985500,1.668500,2.322000,3.990500,1.332500,1.332500,0.561000,0.093500,0.654500,0.053000,0.39250,0.027500,0.15100,0.042000,0.234000,0.202500,1.186500,0.055500,0.655500
859,2020.0,WY,38.137875,0.782375,0.348625,1.13100,0.497625,0.061000,0.558750,0.081750,0.516500,0.282375,0.164500,0.598625,0.723250,1.321750,0.317125,0.317125,0.193125,0.038250,0.231000,0.046250,0.30575,0.028250,0.11300,0.047875,0.105125,0.244000,0.927750,0.030250,0.451875

In [354]:
pollution_annual_df['YEAR'] = pollution_annual_df.YEAR.astype(int)

C:\Users\Nima\AppData\Local\Temp/ipykernel_11208/2253446553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pollution_annual_df['YEAR'] = pollution_annual_df.YEAR.astype(int)

In [366]:
pollution_annual_df = pollution_annual_df.rename(columns={'YEAR': 'Year', 'STATE': 'State'})

In [367]:
pollution_annual_df

,Year,State,PRECIP,N_WET_NH4,N_WET_NO3,N_WET,N_DRY_HNO3,N_DRY_NO3,N_DRY_TNO3,N_DRY_NH4,N_DRY_NH3,N_DRY_NH3NET,N_DRY_NOM,N_DRY_NRED,N_DRY_NOXI,N_DRY,S_WET_SO4,S_WET,S_DRY_SO2,S_DRY_SO4,S_DRY,NA_DRY,NA_WET,MG_DRY,MG_WET,K_DRY,K_WET,CA_DRY,CA_WET,CL_DRY,CL_WET
1,2001,AL,131.225000,2.506000,2.165000,4.67200,4.173000,0.286000,4.460000,0.398000,1.535000,0.791000,1.932000,1.933000,6.391000,8.324000,4.921000,4.921000,6.638000,0.318000,6.956000,0.196000,1.27300,0.046000,0.22300,0.060000,0.551000,0.184000,0.866000,0.106000,2.245000
2,2001,AR,151.199000,1.507000,2.241000,3.74800,3.314000,0.077000,3.391000,0.233000,1.217000,0.678000,1.516000,1.450000,4.907000,6.356000,4.147000,4.147000,1.446000,0.244000,1.690000,0.208000,1.44200,0.038000,0.24000,0.048000,0.526000,0.135000,1.754000,0.092000,2.448000
3,2001,AZ,34.533333,0.549667,0.827333,1.37700,1.498000,0.107333,1.605667,0.113667,0.365667,0.131667,0.253000,0.479333,1.858333,2.337667,0.823667,0.823667,0.369667,0.104333,0.474333,0.126333,0.23300,0.035333,0.09500,0.038667,0.140667,0.269667,0.934667,0.044000,0.423667
4,2001,CA,58.153625,1.176000,0.892625,2.06875,3.764625,0.248125,4.012500,0.226250,2.296750,2.054875,0.449625,2.522625,4.462250,6.984875,0.590750,0.590750,0.419875,0.124625,0.544375,0.288750,0.73975,0.058000,0.10500,0.070250,0.104875,0.261250,0.467375,0.088375,1.249750
5,2001,CO,55.322000,0.772000,1.045000,1.81650,1.412250,0.224000,1.636250,0.175000,0.331500,0.198750,0.282750,0.506500,1.919250,2.425500,0.842750,0.842750,0.274500,0.133000,0.407500,0.095000,0.15750,0.038500,0.08650,0.048500,0.095000,0.275250,0.910750,0.048250,0.270750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,2020,VT,118.453500,1.962500,1.584000,3.54700,1.286000,0.105500,1.391500,0.141000,1.460000,1.300500,0.468000,1.600500,1.859500,3.460500,1.066500,1.066500,0.247000,0.097000,0.344000,0.158500,0.65050,0.039000,0.23350,0.040500,0.347000,0.160500,1.258500,0.145500,1.145000
856,2020,WA,150.606750,0.770000,0.718250,1.48825,0.841250,0.044750,0.886000,0.074500,0.641750,-0.171500,0.414000,0.716000,1.299750,2.015750,0.720750,0.720750,0.227250,0.080500,0.308000,0.125750,2.65325,0.057500,0.31725,0.044750,0.256500,0.064500,0.469250,0.114250,4.828000
857,2020,WI,89.840000,4.528000,1.534000,6.06200,1.163000,0.140000,1.303000,0.143000,3.733000,3.415000,0.422000,3.876000,1.724000,5.601000,1.117000,1.117000,0.307000,0.056000,0.362000,0.054000,0.30500,0.060000,0.35000,0.043000,0.269000,0.370000,3.310000,0.073000,0.512000
858,2020,WV,134.437000,1.895500,1.376500,3.27150,1.266000,0.070500,1.337000,0.145000,1.523000,1.121000,0.985500,1.668500,2.322000,3.990500,1.332500,1.332500,0.561000,0.093500,0.654500,0.053000,0.39250,0.027500,0.15100,0.042000,0.234000,0.202500,1.186500,0.055500,0.655500
859,2020,WY,38.137875,0.782375,0.348625,1.13100,0.497625,0.061000,0.558750,0.081750,0.516500,0.282375,0.164500,0.598625,0.723250,1.321750,0.317125,0.317125,0.193125,0.038250,0.231000,0.046250,0.30575,0.028250,0.11300,0.047875,0.105125,0.244000,0.927750,0.030250,0.451875

In [368]:
pollution_annual_df.to_pickle("D://DTU\DTU_Courses//Second Semester//Advanced BA//Project//ABA-Spring2023//Data//Pickle Files//pollution_Proc_df.pickle")

In [359]:
len(pop_df.State.unique())

50

In [369]:
len(pollution_annual_df.State.unique())

39

In [370]:
len(pop_df.State.unique())

50

In [374]:
len(tax_df.States.unique())

50

In [379]:
tax_df = tax_df.rename(columns={'Description': 'Tax_item_desc','item': 'Tax_item', 'States': 'State'})

In [396]:
list(tax_df['Tax_item_desc'].unique())

['Property Taxes',
 'General Sales and Gross Receipts Taxes',
 'Alcoholic Beverages Sales Tax',
 'Amusements Sales Tax',
 'Insurance Premiums Sales Tax',
 'Motor Fuels Sales Tax',
 'Pari-mutuels Sales Tax',
 'Public Utilities Sales Tax',
 'Tobacco Products Sales Tax',
 'Other Selective Sales and Gross Receipts Taxes',
 'Alcoholic Beverages License',
 'Amusements License',
 'Corporations in General License',
 'Hunting and Fishing License',
 'Motor Vehicles License',
 'Motor Vehicle Operators License',
 'Public Utilities License',
 'Occupation and Businesses License, NEC',
 'Other License Taxes',
 'Individual Income Taxes',
 'Corporation Net Income Taxes',
 'Death and Gift Taxes',
 'Documentary and Stock Transfer Taxes',
 'Severance Taxes',
 'Taxes, NEC']

In [408]:
tax_df['Tax'] = tax_df['Tax'].replace('X', np.nan)
tax_df['Tax'] = tax_df['Tax'].astype(float)

In [412]:
tax_df = tax_df.groupby(['Year', 'State']).agg('sum').reset_index()
tax_df

      Year State         Tax
0     2000    AK   1423287.0
1     2000    AL   6438438.0
2     2000    AR   4870561.0
3     2000    AZ   8100737.0
4     2000    CA  83807959.0
...    ...   ...         ...
1095  2021    VT   4102929.0
1096  2021    WA  32614091.0
1097  2021    WI  22300918.0
1098  2021    WV   6046197.0
1099  2021    WY   1874876.0

[1100 rows x 3 columns]

In [413]:
tax_df.to_pickle("D://DTU\DTU_Courses//Second Semester//Advanced BA//Project//ABA-Spring2023//Data//Pickle Files//tax_Proc_df.pickle")

### joining

In [438]:
tax_df['Year'] = tax_df['Year'].astype(int)

merg_df = demog_df.merge(tax_df, on = ['Year', 'State'], how = 'outer')

In [439]:
type(merg_df['Year'][0])

numpy.int64

In [441]:
merg1_df = disease_df.merge(merg_df, on = ['Year', 'State'], how = 'left')

In [443]:
merged_df = merg1_df.merge(pollution_annual_df, on = ['Year', 'State'], how = 'left')

In [445]:
merged_df.to_pickle("D://DTU\DTU_Courses//Second Semester//Advanced BA//Project//ABA-Spring2023//Data//Pickle Files//merged_df.pickle")

# Working with NULL Years

In [123]:
np.min(disease_df['Year']),np.max(disease_df['Year'])

(2008, 2019)

In [124]:
np.min(demog_df['Year']),np.max(demog_df['Year'])

(2010, 2019)

In [125]:
np.min(pollution_annual_df['Year']),np.max(pollution_annual_df['Year'])

(2001, 2020)

In [126]:
np.min(tax_df['Year']),np.max(tax_df['Year'])

('2000', '2021')

## Filter the overlapping "States" among the different datasets

In [127]:
s1 = set(disease_df['State'].unique())

In [128]:
s2 = set(pollution_annual_df['State'].unique())

In [129]:
diff = list(s1-s2)

In [130]:
disease_df = disease_df[~disease_df['State'].isin(diff)]
demog_df = demog_df[~demog_df['State'].isin(diff)]
tax_df = tax_df[~tax_df['State'].isin(diff)]

In [131]:
# Change year from str to int
tax_df['Year'] = tax_df['Year'].astype(int)

## Filter the overlapping "Year" among the different datasets from 2001 to 2019

In [132]:
tax_df = tax_df[tax_df['Year'].isin(list(range(2001, 2020)))]
pollution_annual_df = pollution_annual_df[pollution_annual_df['Year'].isin(list(range(2001, 2020)))]

## Add the missing values from 2001 to 2009 to demographic df with the same values of year 2010

In [133]:
for y in range(2001, 2010):
    demog_2010 = demog_df[demog_df['Year'] == 2010].iloc[:,1:]
    demog_2010['Year'] = y
    demog_df = pd.concat([demog_df, demog_2010])

In [135]:
merge_df = pd.merge(tax_df, demog_df, on=['Year', 'State'])

In [137]:
merge_df = pd.merge(merge_df, pollution_annual_df, on=['Year', 'State'])

In [143]:
with open(path+'features.pickle', 'wb') as f:
    pickle.dump(merge_df, f, protocol=pickle.HIGHEST_PROTOCOL)

In [144]:
with open(path+'disease_Proc_df.pickle', 'wb') as f:
    pickle.dump(disease_df, f, protocol=pickle.HIGHEST_PROTOCOL)

In [145]:
with open(path+'pollution_Proc_df.pickle', 'wb') as f:
    pickle.dump(pollution_annual_df, f, protocol=pickle.HIGHEST_PROTOCOL)

In [146]:
with open(path+'tax_Proc_df.pickle', 'wb') as f:
    pickle.dump(tax_df, f, protocol=pickle.HIGHEST_PROTOCOL)

In [147]:
with open(path+'demog_Proc_df.pickle', 'wb') as f:
    pickle.dump(demog_df, f, protocol=pickle.HIGHEST_PROTOCOL)